##############
# IMPORTS
############## 
import threading, copy

from .lexer import Error

from .semantic import (
    NumNode, DatatypeNode, StringNode, BoolNode, NullNode, ExponentNode, BinOpNode, 
    RelOpNode, LogOpNode, UnaryOpNode, IdNode, VarDecNode, VarAssignNode, ClanDecNode, 
    ClanLiteralNode, ClanAccessNode, ClanIndexAssignNode, 
    CurseDecNode, CurseDomainNode, ParamNode, BodyNode, CurseCallNode, 
    InvokeNode, CaptureNode, CleaveNode, DismantleNode, LenNode, RecallNode, DismissNode, 
    HopNode, VowNode, ElseVow, ElseNode, BoogieNode, WoogieTrueNode, WoogieNode, 
    DefaultCaseNode, SustainNode, PerformSustainNode, CycleNode, CycleConditionNode, SymbolTable,
)

##############
# ERRORS
############## 
    
class SemanticError(Error):
    def __init__(self, pos_start, pos_end, details=''):
        super().__init__(pos_start, pos_end, 'Semantic Error', details)

class RTError(Error):
    def __init__(self, pos_start, pos_end, details=''):
        super().__init__(pos_start, pos_end, 'Runtime Error', details)

class ContinueIteration(Exception):
    pass

class ReturnException(Exception):
    def __init__(self, value=None):
        self.value = value

####################################
######## Interpreter Class #########
####################################
# > This class is responsible for interpreting the AST (Abstract Syntax Tree) generated by the parser.
# > Similarly to the semantic analyzer, it traverses the tree (pre-order) and executes the code represented by the nodes.
# > Each visit_<node_type> corresponds to a specific method for interpreting that node type.
# > Example: visit_InvokeNode has logic that will supposedly print what's in its node.value to the terminal.
#
# > Note: It has a special utility method "evaluate_node" that is used to evaluate the value of a node.
# > Example: if a node is a BinOpNode, it will evaluate the left and right nodes and apply the operator and return the result value.
# >          if a node is a CurseCallNode, it will evaluate the arguments and apply the curse's body logic, and return the result value.
# > Also supports nodes that are not directly executable, but rather represent an expression.
####################################

class DOMInterpreter: 
    def visit(self, node, parent=None):
        if hasattr(self, 'error') and self.error:
            return None 
    
        method_name = f'visit_{type(node).__name__}'
        visitor = getattr(self, method_name, self.generic_visit)
        return visitor(node, parent)

    def generic_visit(self, node, parent):
        if parent is None:
            print(f"Visiting root node: {type(node).__name__}")
        self.visit_children(node)

    def visit_children(self, node):
        for child in node.children:
            print(f"Child node: {type(child).__name__}, Parent node: {type(node).__name__}")
            self.visit(child, node)

class CodeRunner(DOMInterpreter):
    def __init__(self, symbol_table, socketio=None):
        self.symbol_table = symbol_table
        self.output = []
        self.error = None
        self.socketio = socketio
        self.input_events = {}
        self.input_values = {}
        self.current_node = None  
        self.current_parent = None  
        self.processed_capture_nodes = set()  # Set to keep track of processed CaptureNodes

    def visit_DatatypeNode(self, node, parent):
        print(f"Visiting DatatypeNode with type: {node.datatype}")
        self.visit_children(node)
        print(f"Exiting DatatypeNode")

    def visit_StringNode(self, node, parent):
        print(f"Visiting StringNode with value: {node.value}")
        return node.value

    def visit_BoolNode(self, node, parent):
        print(f"Visiting BoolNode with value: {node.value}")
        self.visit_children(node)
        print(f"Exiting BoolNode")

    def visit_NullNode(self, node, parent):
        print(f"Visiting NullNode")
        self.visit_children(node)
        return None

    def visit_NumNode(self, node, parent):
        print(f"Visiting NumNode with value: {node.value}")
        return node.value

    def visit_ExponentNode(self, node, parent):
        print(f"Exiting ExponentNode")

    def visit_BinOpNode(self, node, parent):
        print(f"Visiting BinOpNode with operator: {node.op}")
        self.visit_children(node)
        print(f"Exiting BinOpNode")

    def visit_RelOpNode(self, node, parent):
        print(f"Visiting RelOpNode with operator: {node.op}")
        print(f"Exiting RelOpNode")

    def visit_LogOpNode(self, node, parent):
        print(f"Visiting LogOpNode with operator: {node.op}")
        print(f"Exiting LogOpNode")

    def visit_UnaryOpNode(self, node, parent):
        print(f"Visiting UnaryOpNode with operator: {node.op.op}")
        value, error = self.evaluate_node(node.expr)
        if error:
            self.error = error
            return

        # Update the symbol table if the operation modifies the value
        if node.op.op in ['++', '--']:
            if isinstance(node.expr, IdNode):
                symbol = self.symbol_table.get(node.expr.name)
                if symbol is None:
                    self.error = SemanticError(node.pos_start, node.pos_end, f"Variable '{node.expr.name}' is not declared")
                    return
                if isinstance(symbol, VarDecNode):
                    updated_value = value + 1 if node.op.op == '++' else value - 1
                    value_node = NumNode(updated_value, None, None)
                    updated_symbol = VarDecNode(
                        symbol.restrict, symbol.datatype, symbol.name, value_node, symbol.pos_start, symbol.pos_end
                    )
                    self.symbol_table.set(node.expr.name, updated_symbol)
                    print(f"Updated value '{updated_value}' for variable '{node.expr.name}' in symbol table")

        return value, None

    def visit_IdNode(self, node, parent):
        print(f"Visiting IdNode with name: {node.name}")
        # Check if the variable is declared in the symbol table
        symbol = self.symbol_table.get(node.name);
        if self.symbol_table.get(node.name) is None:
            self.error = SemanticError(node.pos_start, node.pos_end, f"Variable '{node.name}' is not declared")
            return None
        if isinstance(symbol, VarDecNode):
            # If the variable is declared, return its value
            print(f"IdNode '{node.name}' found in symbol table")
            return symbol.value
        return None

    def visit_VarDecNode(self, node, parent):
        print(f"Visiting VarDecNode with type: {node.datatype}")
        # true parent
        true_parent = parent
        while true_parent and not isinstance(true_parent, (CurseDomainNode, CurseDecNode)):
            true_parent = true_parent.parent

        if true_parent is None:
            pass
        else:
            var_dec_node = self.symbol_table.get_local(node.name)
            if not var_dec_node and parent is not None:
                self.symbol_table.set_local(node.name, node)  # Store the VarDecNode object itself
                var_dec_node = self.symbol_table.get(node.name)
            
            value, error = self.evaluate_node(var_dec_node.value)
            if error:
                self.error = error
                return

            if var_dec_node.datatype == 'int' and isinstance(value, float):
                value = int(value)  # Convert float to integer
                print(f"Converted float value to integer for variable '{node.name}'")

            value_node = None
            if isinstance(value, int):
                if value > 9999999999999999:
                    self.error = RTError(node.pos_start, node.pos_end, f'Integer value exceeded maximum limit of 16 digits')
                    return
                value_node = NumNode(value, None, None)
            elif isinstance(value, float):
                if value > 999999999:
                    self.error = RTError(node.pos_start, node.pos_end, f"Float's significant value exceeded maximum limit of 9 digits")
                    return
                decimal_part = str(value).split('.')[-1]
                if len(decimal_part) > 7:
                    value = round(value, 7)
                value_node = NumNode(value, None, None)
            elif isinstance(value, str):
                value_node = StringNode(value, None, None)
            elif isinstance(value, bool):
                value_node = BoolNode(value, None, None)
            elif value is None:
                value_node = NullNode(None, None, None)

            # Update the value in the variable declaration node
            var_dec_node_copy = VarDecNode(False, var_dec_node.datatype, var_dec_node.name, value_node, var_dec_node.pos_start, var_dec_node.pos_end)
            self.symbol_table.set(node.name, var_dec_node_copy)  # Update the symbol table with the new value
            print(f'Value: {var_dec_node.value}')
            print(f"Updated value '{value}' for variable '{node.name}' in symbol table")

        self.visit_children(node)
        print(f"Exiting VarDecNode")

    def visit_VarAssignNode(self, node, parent):
        print(f"Visiting VarAssignNode with name: {node.name}")
        value, error = self.evaluate_node(node.value)
        if error:
            self.error = error
            return
        # Retrieve the variable declaration node from the symbol table
        var_dec_node = self.symbol_table.get(node.name)
        if var_dec_node is None:
            self.error = SemanticError(node.pos_start, node.pos_end, f"Variable '{node.name}' is not declared")
            return
        # Check if the variable is of integer type
        if var_dec_node.datatype == 'int' and isinstance(value, float):
            value = int(value)  # Convert float to integer
            print(f"Converted float value to integer for variable '{node.name}'")

        value_node = None
        if isinstance(value, (int, float)):
            value_node = NumNode(value, None, None)
        elif isinstance(value, str):
            value_node = StringNode(value, None, None)
        elif isinstance(value, bool):
            value_node = BoolNode(value, None, None)
        elif value is None:
            value_node = NullNode(None, None, None)

        # Update the value in the variable declaration node
        var_dec_node_copy = VarDecNode(False, var_dec_node.datatype, var_dec_node.name, value_node, var_dec_node.pos_start, var_dec_node.pos_end)
        self.symbol_table.set(node.name, var_dec_node_copy)  # Update the symbol table with the new value
        print(f"Updated value '{value}' for variable '{node.name}' in symbol table")
        print(f"Exiting VarAssignNode")

    def visit_ClanDecNode(self, node, parent):
        print(f"Visiting ClanDecNode with name: {node.name}")
        true_parent = parent
        while true_parent and not isinstance(true_parent, (CurseDomainNode, CurseDecNode)):
            true_parent = true_parent.parent

        if true_parent is None or not isinstance(true_parent, (CurseDomainNode, CurseDecNode)):
            pass
        else:
            if self.symbol_table.get(node.name):
                self.error = SemanticError(node.pos_start, node.pos_end, f"Variable '{node.name}' already declared")
            else:
                self.symbol_table.set(node.name, node)

        # default values
        if not node.size1 and not node.size2:
            if isinstance(node.initial_values, CleaveNode):
                new_clan, error = self.evaluate_node(node.initial_values)
                if error:
                    self.error = error
                    return
                if not isinstance(new_clan, ClanLiteralNode):
                    self.error = SemanticError(node.pos_start, node.pos_end, "Not a clan")
                node.initial_values = new_clan
            elif isinstance(node.initial_values, DismantleNode):
                new_clan, error = self.evaluate_node(node.initial_values)
                if error:
                    self.error = error
                    return
                if not isinstance(new_clan, ClanLiteralNode):
                    self.error = SemanticError(node.pos_start, node.pos_end, "Not a clan")
                node.initial_values = new_clan
            elif not isinstance(node.initial_values, ClanLiteralNode):
                self.error = SemanticError(node.pos_start, node.pos_end, "Invalid clan value")
            

        # Handle single-dimensional array
        if node.size1 and not node.size2:
            size1_value, error = self.evaluate_node(node.size1)
            if error:
                self.error = error
                return
            if size1_value is not None:
                if isinstance(node.initial_values, CleaveNode):
                    new_clan, error = self.evaluate_node(node.initial_values)
                    if error:
                        self.error = error
                        return
                    if not isinstance(new_clan, ClanLiteralNode):
                        self.error = SemanticError(node.pos_start, node.pos_end, "Not a clan")
                    if len(new_clan.values) > size1_value:
                        self.error = SemanticError(node.pos_start, node.pos_end, f"Array out of index 1: size1 is {size1_value}, but got {len(new_clan.values)} initial values")
                    else:
                        # Fill missing values
                        while len(new_clan.values) < size1_value:
                            if node.datatype == 'int':
                                new_clan.values.append(NumNode(0))
                            elif node.datatype == 'float':
                                new_clan.values.append(NumNode(0.0))
                            elif node.datatype == 'string':
                                new_clan.values.append(StringNode("null"))
                            elif node.datatype == 'bool':
                                new_clan.values.append(BoolNode(False))
                        node.initial_values = new_clan
                elif isinstance(node.initial_values, DismantleNode):
                    print(f'I REACHED HEREEEEEEEEE')
                    new_clan, error = self.evaluate_node(node.initial_values)
                    if error:
                        self.error = error
                        return
                    if not isinstance(new_clan, ClanLiteralNode):
                        self.error = SemanticError(node.pos_start, node.pos_end, "Not a clan")
                    if len(new_clan.values) > size1_value:
                        self.error = SemanticError(node.pos_start, node.pos_end, f"Array out of index 2: size1 is {size1_value}, but got {len(new_clan.values)} initial values")
                    else:
                        # Fill missing values
                        while len(new_clan.values) < size1_value:
                            if node.datatype == 'int':
                                new_clan.values.append(NumNode(0))
                            elif node.datatype == 'float':
                                new_clan.values.append(NumNode(0.0))
                            elif node.datatype == 'string':
                                new_clan.values.append(StringNode("null"))
                            elif node.datatype == 'bool':
                                new_clan.values.append(BoolNode(False))
                        node.initial_values = new_clan
                elif not isinstance(node.initial_values, ClanLiteralNode):
                    self.error = SemanticError(node.pos_start, node.pos_end, "Cannot initialize multi-dimensional array with single-dimensional size")
                elif size1_value <=0:
                    self.error = (SemanticError(node.pos_start, node.pos_end, f"Array size must be greater than 0"))
                elif len(node.initial_values.values) > size1_value:
                    self.error = SemanticError(node.pos_start, node.pos_end, f"Array out of index 3: size1 is {size1_value}, but got {len(node.initial_values.values)} initial values")
                else:
                    # Fill missing values
                    while len(node.initial_values.values) < size1_value:
                        if node.datatype == 'int':
                            node.initial_values.values.append(NumNode(0))
                        elif node.datatype == 'float':
                            node.initial_values.values.append(NumNode(0.0))
                        elif node.datatype == 'string':
                            node.initial_values.values.append(StringNode("null"))
                        elif node.datatype == 'bool':
                            node.initial_values.values.append(BoolNode(False))

        # Handle multi-dimensional array
        if node.size1 and node.size2:
            size1_value, error = self.evaluate_node(node.size1)
            if error:
                self.error = error
                return
            size2_value, error = self.evaluate_node(node.size2)
            if error:
                self.error = error
                return
            if size1_value is not None and size2_value is not None:
                if len(node.initial_values) > size1_value:
                    self.error = SemanticError(node.pos_start, node.pos_end, f"Array out of index 4: size1 is {size1_value}, but got {len(node.initial_values)} initial values")
                if len(node.initial_values) < size1_value:
                    while len(node.initial_values) < size1_value:
                        clan_literal = ClanLiteralNode([])
                        if node.datatype == 'int':
                            clan_literal.values.append(NumNode(0))
                        elif node.datatype == 'float':
                            clan_literal.values.append(NumNode(0.0))
                        elif node.datatype == 'string':
                            clan_literal.values.append(StringNode("null"))
                        elif node.datatype == 'bool':
                            clan_literal.values.append(BoolNode(False))
                        node.initial_values.append(clan_literal)

                for inner_node in node.initial_values: #FIXME: what if the clan literal is not there? int num[2][2] = {{1,2,3}};
                    if not isinstance(inner_node, ClanLiteralNode):
                        self.error = SemanticError(node.pos_start, node.pos_end, "Expected ClanLiteralNode for multi-dimensional array")
                    if len(inner_node.values) > size2_value:
                        self.error = SemanticError(inner_node.pos_start, inner_node.pos_end, f"Array out of index 3: size2 is {size2_value}, but got {len(inner_node.values)} initial values")
                    else:
                        # Fill missing values
                        while len(inner_node.values) < size2_value:
                            if node.datatype == 'int':
                                inner_node.values.append(NumNode(0, None, None))
                            elif node.datatype == 'float':
                                inner_node.values.append(NumNode(0.0, None, None))
                            elif node.datatype == 'string':
                                inner_node.values.append(StringNode("null", None, None))
                            elif node.datatype == 'bool':
                                inner_node.values.append(BoolNode(False, None, None))
        print(f"Exiting ClanDecNode")

    def visit_ClanLiteralNode(self, node, parent):
        print(f"Visiting ClanLiteralNode with values: {node.values}")
        self.visit_children(node)
        print(f"Exiting ClanLiteralNode")

    def visit_ClanIndexNode(self, node, parent):
        print(f"Visiting ClanIndexNode with index: {node.index}")
        self.visit_children(node)
        print(f"Exiting ClanIndexNode")

    def visit_ClanSizeNode(self, node, parent):
        print(f"Visiting ClanSizeNode with size: {node.size}")
        self.visit_children(node)
        print(f"Exiting ClanSizeNode")

    def visit_ClanAccessNode(self, node, parent):
        print(f"Visiting ClanAccessNode with name: {node.name}")
        self.visit_children(node)
        print(f"Exiting ClanAccessNode")

    def visit_ClanIndexAssignNode(self, node, parent):
        print(f"Visiting ClanIndexAssignNode with name: {node.name}")
        clan = self.symbol_table.get(node.name)
        if clan is None:
            self.error = SemanticError(node.pos_start, node.pos_end, f"Clan '{node.name}' is not declared")
            return

        if not isinstance(clan, ClanDecNode):
            self.error = SemanticError(node.pos_start, node.pos_end, f"'{node.name}' is not a clan")
            return

        index1, error = self.evaluate_node(node.index1)
        if error:
            self.error = error
            return

        size1, error = self.evaluate_node(clan.size1)
        if error:
            self.error = error
            return

        if not isinstance(index1, int) or index1 < 0 or (clan.size1 and index1 >= size1):
            self.error = SemanticError(node.pos_start, node.pos_end, f"Index 1 out of bounds for clan '{node.name}'")
            return

        if node.index2:
            index2, error = self.evaluate_node(node.index2)
            if error:
                self.error = error
                return

            size2, error = self.evaluate_node(clan.size2)
            if error:
                self.error = error
                return

            if not isinstance(index2, int) or index2 < 0 or (clan.size2 and index2 >= size2):
                self.error = SemanticError(node.pos_start, node.pos_end, f"Index 2 out of bounds for clan '{node.name}'")
                return

            value, error = self.evaluate_node(node.value)
            if error:
                self.error = error
                return

            try:
                clan.initial_values[index1].values[index2] = value
                print(f"Updated clan '{node.name}' at [{index1}][{index2}] with value: {value}")
            except IndexError:
                self.error = SemanticError(node.pos_start, node.pos_end, f"Invalid access at [{index1}][{index2}] for clan '{node.name}'")
        else:
            value, error = self.evaluate_node(node.value)
            if error:
                self.error = error
                return
            if clan.datatype == 'int' and isinstance(value, float):
                value = int(value)
            elif clan.datatype == 'float' and isinstance(value, int):
                value = float(value)
            elif clan.datatype != self.infer_type(value):
                self.error = SemanticError(node.pos_start, node.pos_end, f"Type mismatch: expected {clan.datatype}, got {self.infer_type(value)}")
                return
            try:
                print(f'BEFORE UPDATING CLAN AT [{index1}] VALUE: {clan.initial_values.values[index1]}')
                clan.initial_values.values[index1] = value
                print(f"Updated clan '{node.name}' at [{index1}] with value: {value}")
                print(f'AFTER UPDATING CLAN AT [{index1}] VALUE: {clan.initial_values.values[index1]}')
            except IndexError:
                self.error = SemanticError(node.pos_start, node.pos_end, f"Invalid access at [{index1}] for clan '{node.name}'")

    def visit_CurseDecNode(self, node, parent):
        print(f"Visiting CurseDecNode with name: {node.name}")
        true_parent = parent
        while true_parent and not isinstance(true_parent, (CurseDomainNode, CurseDecNode)):
            true_parent = true_parent.parent

        if true_parent is None or not isinstance(true_parent, (CurseDomainNode, CurseDecNode)):
            pass
        else:
            if self.symbol_table.get(node.name) and not isinstance(parent.parent, (CurseDecNode, CurseDomainNode)):
                self.errors = SemanticError(node.pos_start, node.pos_end, f"Curse '{node.name}' already declared")
            else:
                self.symbol_table.set(node.name, node)  # Store the CurseDecNode object itself
        print(f"Exiting CurseDecNode")

    def visit_CurseDomainNode(self, node, parent):
        print(f"Visiting CurseDomainNode")
        self.visit_children(node)
        print(f"Exiting CurseDomainNode")

    def visit_ParamNode(self, node, parent):
        print(f"Visiting ParamNode with name: {node.name}")
        self.visit_children(node)
        print(f"Exiting ParamNode")

    def visit_BodyNode(self, node, parent):
        print(f"Visiting BodyNode")
        print(f"BodyNode Parent: {type(parent)}")
        self.symbol_table.push()  # Enter new scope for body
    
        for child in list(node.children):
            if isinstance(child, CurseDecNode):
                if self.symbol_table.get(child.name):
                    self.errors.append(SemanticError(child.pos_start, child.pos_end, f"Curse '{child.name}' already declared in this scope"))
                else:
                    self.symbol_table.set(child.name, child)

        self.visit_children(node)
        self.symbol_table.pop()  # Exit body scope
        print(f"Exiting BodyNode")

    def visit_CurseCallNode(self, node, parent):
        print(f"Visiting CurseCallNode with name: {node.name}")

        # Retrieve the curse declaration from the symbol table
        curse_dec_node = self.symbol_table.get(node.name)
        if curse_dec_node is None:
            self.error = SemanticError(node.pos_start, node.pos_end, f"Curse '{node.name}' is not declared")
            return None
        
        if curse_dec_node.datatype is not None:
            return # early return because this visit method is for void curse calls only so if it has a datatype, just ignore.

        # Evaluate arguments and map them to parameters
        self.symbol_table.push()  # Enter new scope for curse call
        try:
            for param, arg in zip(curse_dec_node.parameters, node.arguments):
                arg_value, error = self.evaluate_node(arg)
                if error:
                    self.error = error
                    return None

                print(f"Parameter '{param.name}' set to: {arg_value}")
                self.symbol_table.set(param.name, VarDecNode(False, param.datatype, param.name, NumNode(arg_value, None, None), param.pos_start, param.pos_end))

            self.visit(curse_dec_node.body, curse_dec_node)
            return
        except RecursionError:
            self.error = SemanticError(node.pos_start, node.pos_end, f"Recursion limit exceeded in curse '{node.name}'")
            return
        finally:
            self.symbol_table.pop()  # Exit the scope after the curse call

    def visit_InvokeNode(self, node, parent):
        print(f"Visiting InvokeNode")
        value = ''
        if isinstance(node.value, list):
            for list_item in node.value:
                temp, error = self.evaluate_node(list_item)
                if error:
                    self.error = error
                    break
                if isinstance(temp, str):
                    value += temp
                else: 
                    value += str(temp)
        else: 
            value, error = self.evaluate_node(node.value)
            if value is None:
                value = node.value
            if error:
                self.error = error
                return

        # Convert to string representation
        if hasattr(value, 'to_string'):
            output_text = value.to_string()
        else:
            output_text = str(value)
            
        # Add to accumulated output
        self.output.append(output_text)
        
        # Emit real-time update via socket
        if self.socketio:
            self.socketio.emit('output_update', {'output': output_text})
            
        print(f'Invocation: {output_text}')
        print(f"Exiting InvokeNode")

    def visit_CaptureNode(self, node, parent):
        print(f"Visiting CaptureNode with name: {node.name}")

        if isinstance(node.name, ClanAccessNode):
            clan = self.symbol_table.get(node.name.name)
            if clan is None:
                self.error = SemanticError(node.pos_start, node.pos_end, f"Clan '{node.name.name}' is not declared")
                return

            if not isinstance(clan, ClanDecNode):
                self.error = SemanticError(node.pos_start, node.pos_end, f"'{node.name.name}' is not a clan")
                return

            index1, error = self.evaluate_node(node.name.index1)
            if error:
                self.error = error
                return

            size1, error = self.evaluate_node(clan.size1)
            if error:
                self.error = error
                return

            if not isinstance(index1, int) or index1 < 0 or (clan.size1 and index1 >= size1):
                self.error = SemanticError(node.pos_start, node.pos_end, f"Index 1 out of bounds for clan '{node.name.name}'")
                return

            if node.name.index2:
                index2, error = self.evaluate_node(node.name.index2)
                if error:
                    self.error = error
                    return

                size2, error = self.evaluate_node(clan.size2)
                if error:
                    self.error = error
                    return

                if not isinstance(index2, int) or index2 < 0 or (clan.size2 and index2 >= size2):
                    self.error = SemanticError(node.pos_start, node.pos_end, f"Index 2 out of bounds for clan '{node.name.name}'")
                    return

            if self.socketio:
                self.socketio.emit('capture_input', {'var_name': node.name.name})

            user_input = self.wait_for_input(node.name.name)

            if user_input is not None:
                try:
                    if clan.datatype == 'int':
                        user_input = NumNode(int(user_input))
                        if user_input.value > 9999999999999999:
                            self.error = SemanticError(node.pos_start, node.pos_end, f"Input value too large for integer '{node.name.name}', limit is 16 digits")
                            return
                    elif clan.datatype == 'float':
                        user_input = NumNode(float(user_input))
                        if user_input.value > 999999999:
                            self.error = SemanticError(node.pos_start, node.pos_end, f"Input value too large for float '{node.name.name}', limit is 9 digits")
                            return
                        decimal_part = str(user_input.value).split('.')[-1]
                        if len(decimal_part) > 7:
                            truncated_value = round(user_input.value, 7)
                            user_input = NumNode(truncated_value)
                    elif clan.datatype == 'string':
                        user_input = StringNode(str(user_input))
                    elif clan.datatype == 'bool':
                        user_input = user_input.lower()
                        if user_input == 'true':
                            user_input = BoolNode(True)
                        elif user_input == 'false':
                            user_input = BoolNode(False)
                        else:
                            self.error = SemanticError(node.pos_start, node.pos_end, f"Invalid input for clan '{node.name.name}': expected bool")
                            return
                except:
                    self.error = SemanticError(node.pos_start, node.pos_end, f"Invalid input for clan '{node.name.name}': expected int")
                    return

                if node.name.index2:
                    try:
                        clan.initial_values[index1].values[index2] = user_input
                        print(f"Updated clan '{node.name.name}' at [{index1}][{index2}] with value: {user_input}")
                    except IndexError:
                        self.error = SemanticError(node.pos_start, node.pos_end, f"Invalid access at [{index1}][{index2}] for clan '{node.name.name}'")
                else:
                    try:
                        clan.initial_values.values[index1] = user_input
                        print(f"Updated clan '{node.name.name}' at [{index1}] with value: {user_input}")
                    except IndexError:
                        self.error = SemanticError(node.pos_start, node.pos_end, f"Invalid access at [{index1}] for clan '{node.name.name}'")
        else:
            var_symbol = self.symbol_table.get(node.name.name)
            print(f"CaptureNode var_symbol: {var_symbol}")
            var_name = var_symbol.name if isinstance(var_symbol, (VarDecNode, ClanDecNode)) else None
            var_type = var_symbol.datatype if isinstance(var_symbol, (VarDecNode, ClanDecNode)) else None

            if self.socketio:
                self.socketio.emit('capture_input', {'var_name': var_name})

            user_input = self.wait_for_input(var_name)

            if user_input is not None:
                try:
                    if var_type == 'int':
                        user_input = NumNode(int(user_input))
                        if user_input.value > 99999999999999999:
                            self.error = SemanticError(node.pos_start, node.pos_end, f"Input value too large for integer '{var_name}', limit is 16 digits")
                            return
                        if not isinstance(user_input, NumNode):
                            self.error = SemanticError(node.pos_start, node.pos_end, f"Invalid input for variable '{var_name}', expected int")
                            return
                    elif var_type == 'float':
                        user_input = NumNode(float(user_input))
                        if user_input.value > 999999999:
                            self.error = SemanticError(node.pos_start, node.pos_end, f"Input value too large for float '{var_name}', limit is 9 digits")
                            return
                        decimal_part = str(user_input.value).split('.')[-1]
                        if len(decimal_part) > 7:
                            truncated_value = round(user_input.value, 7)
                            user_input = NumNode(truncated_value)
                        if not isinstance(user_input, NumNode):
                            self.error = SemanticError(node.pos_start, node.pos_end, f"Invalid input for variable '{var_name}', expected float")
                            return
                    elif var_type == 'string':
                        user_input = StringNode(str(user_input))
                    elif var_type == 'bool':
                        user_input = user_input.lower()
                        if user_input == 'true':
                            user_input = BoolNode(True)
                        elif user_input == 'false':
                            user_input = BoolNode(False)
                        else:
                            self.error = SemanticError(node.pos_start, node.pos_end, f"Invalid input for variable '{var_name}', expected bool")
                            return
                except:
                    self.error = SemanticError(node.pos_start, node.pos_end, f"Invalid input for variable '{var_name}', expected int")
                    return

                var_symbol_copy = VarDecNode(False, var_symbol.datatype, var_symbol.name, user_input, var_symbol.pos_start, var_symbol.pos_end)
                self.symbol_table.set(var_name, var_symbol_copy)
            
    def visit_CleaveNode(self, node, parent):
        print(f"Visiting CleaveNode with arg: {node.arg1}")
        print(f"Exiting CleaveNode")

    def visit_DismantleNode(self, node, parent):
        print(f"Visiting DismantleNode with name: {node.name}")
        print(f"Exiting DismantleNode")

    def visit_LenNode(self, node, parent):
        print(f"Visiting LenNode with name: {node.name}")
        print(f"Exiting LenNode")

    def visit_RecallNode(self, node, parent):
        print(f"Visiting RecallNode")
        value = None
        if node.value:
            value, error = self.evaluate_node(node.value)
            if error:
                self.error = error
                return
        raise ReturnException(value)  # return a value from the curse through custom error return exception

    def visit_DismissNode(self, node, parent):
        print(f"Visiting DismissNode")
        raise StopIteration  # Use StopIteration to simulate a break in the loop

    def visit_HopNode(self, node, parent):
        print(f"Visiting HopNode")
        raise ContinueIteration  # Use a custom exception to simulate a continue in the loop

    def visit_VowNode(self, node, parent):
        print(f"Visiting VowNode")
        condition_value, error = self.evaluate_node(node.condition)
        if error:
            self.error = error
            return

        print(f"Vow condition evaluated to: {condition_value}")
        if condition_value:
            print(f'Vow Condition True, executing body')
            self.visit(node.body, node)
            return
        else:
            for else_vow in node.else_vows:
                else_condition_value, error = self.evaluate_node(else_vow.condition)
                if error:
                    self.error = error
                    return

                print(f"Else Vow condition evaluated to: {else_condition_value}")
                if else_condition_value:
                    print(f'Else Vow Condition True: executing body')
                    self.visit(else_vow.body, else_vow)
                    return
            else:
                if node.else_body:
                    print(f'No condition was true, executing else body')
                    self.visit(node.else_body.body, node.else_body)
                    return

        print(f"Exiting VowNode")

    def visit_ElseVow(self, node, parent):
        pass

    def visit_ElseNode(self, node, parent):
        pass

    def visit_BoogieNode(self, node, parent):
        print(f"Visiting BoogieNode")
        expression_value, error = self.evaluate_node(node.expression) if node.expression else (None, None)
        if error:
            self.error = error
            return

        for case in node.cases:
            if isinstance(case, WoogieNode):
                case_condition_value, error = self.evaluate_node(case.condition)
                if error:
                    self.error = error
                    return

                if expression_value == case_condition_value:
                    try:
                        self.visit(case.body, node)
                    except StopIteration:
                        break
            elif isinstance(case, WoogieTrueNode):
                case_condition_value, error = self.evaluate_node(case.condition)
                if error:
                    self.error = error
                    return

                if case_condition_value:
                    try: 
                        self.visit(case.body, node)
                    except StopIteration:
                        break
            elif isinstance(case, DefaultCaseNode):
                self.visit(case.body, node)
                break

        print(f"Exiting BoogieNode")

    def visit_WoogieTrueNode(self, node, parent):
        print(f"Visiting WoogieTrueNode")
        condition_value, error = self.evaluate_node(node.condition)
        if error:
            self.error = error
            return

        if condition_value:
            self.visit(node.body, node)

        print(f"Exiting WoogieTrueNode")

    def visit_WoogieNode(self, node, parent):
        print(f"Visiting WoogieNode")
        condition_value, error = self.evaluate_node(node.condition)
        if error:
            self.error = error
            return

        if condition_value:
            self.visit(node.body, node)

        print(f"Exiting WoogieNode")

    def visit_DefaultCaseNode(self, node, parent):
        print(f"Visiting DefaultCaseNode")
        self.visit(node.body, node)
        print(f"Exiting DefaultCaseNode")

    def visit_SustainNode(self, node, parent):
        print(f"Visiting SustainNode")
        while True:
            try: 
                condition_value, error = self.evaluate_node(node.condition)
                if error:
                    self.error = error
                    break

                if not condition_value:
                    break

                self.visit(node.body, node)
            except ContinueIteration:
                continue
            except StopIteration:
                break
        print(f"Exiting SustainNode")

    def visit_PerformSustainNode(self, node, parent):
        print(f"Visiting PerformSustainNode")
        while True:
            try: 
                # Execute the body of the loop
                self.visit(node.body, node)
                
                # Evaluate the condition
                condition_value, error = self.evaluate_node(node.condition)
                if error:
                    self.error = error
                    break
                
                # If the condition is false, exit the loop
                if not condition_value:
                    break
            except ContinueIteration:
                continue
            except StopIteration:
                break

        print(f"Exiting PerformSustainNode")

    def visit_CycleNode(self, node, parent):
        print(f"Visiting CycleNode")
        self.symbol_table.push()  # Enter new scope for cycle body
        print(f'Symbol Stack: {self.symbol_table.scopes}')
        # Visit the CycleConditionNode first
        self.visit(node.cycle_condition, node)
        # Execute the body of the loop while the condition is true
        while True:
            try:
                condition_value, error = self.evaluate_node(node.cycle_condition.condition)
                if error:
                    self.error = error
                    break
                if not condition_value:
                    break
                self.visit(node.body, node)
                # Execute the iteration part of the CycleConditionNode
                self.visit(node.cycle_condition.iteration, node)
            except ContinueIteration:
                continue
            except StopIteration:
                break
        self.symbol_table.pop()
        print(f'New Symbol Stack: {self.symbol_table.scopes}')
        print(f"Exiting CycleNode")

    def visit_CycleConditionNode(self, node, parent):
        print(f"Visiting CycleConditionNode")
        # Execute the initialization part of the CycleConditionNode
        self.visit(node.init, node)
        print(f"Exiting CycleConditionNode")

    def provide_input(self, var_name, value):
        self.input_values[var_name] = value
        if var_name in self.input_events:
            self.input_events[var_name].set()

    def wait_for_input(self, var_name):
        event = threading.Event()
        self.input_events[var_name] = event

        event.wait()

        value = self.input_values.pop(var_name, "")
        self.input_events.pop(var_name, None)
        return value

    def infer_type(self, node):
        if isinstance(node, NumNode):
            return 'int' if isinstance(node.value, int) else 'float'
        elif isinstance(node, StringNode):
            return 'string'
        elif isinstance(node, BoolNode):
            return 'bool'
        elif isinstance(node, RelOpNode):
            return 'bool'
        elif isinstance(node, LogOpNode):
            return 'bool'
        elif isinstance(node, NullNode):
            return 'null'
        elif isinstance(node, IdNode):
           if self.symbol_table.get_type(node.name):
               return self.symbol_table.get_type(node.name)
           else: return 'unknown'
        elif isinstance(node, BinOpNode):
            if node.op in ['<', '>', '<=', '>=', '==', '!=', '!', '&&', '||']:
                return 'bool'
            left = node.left
            right = node.right
            left_type = self.infer_type(left)
            right_type = self.infer_type(right)
            if left_type == right_type:
                return left_type
            else:
                if left_type == 'bool' and right_type == 'bool':
                    return 'bool'
                elif left_type == 'int' and right_type == 'bool':
                    return 'int'
                elif left_type == 'bool' and right_type == 'int':
                    return 'int'
                elif left_type == 'float' and right_type == 'bool':
                    return 'float'
                elif left_type == 'bool' and right_type == 'float':
                    return 'float'
                elif left_type == 'float' or right_type == 'float':
                    return 'float'
                elif left_type == 'int' or right_type == 'int':
                    return 'int'
                elif left_type == 'string' or right_type == 'string':
                    return 'string'
                else:
                    return 'unknown'
        elif isinstance(node, UnaryOpNode):
            return self.infer_type(node.expr)
        elif isinstance(node, ClanAccessNode):
            return self.symbol_table.get_type(node.name)
        elif isinstance(node, CurseCallNode):
            curse_node = self.symbol_table.get(node.name)
            if isinstance(curse_node, CurseDecNode):
                return curse_node.datatype
            return 'unknown'
        elif isinstance(node, str):
            return 'string'
        elif isinstance(node, bool):
            return 'bool'
        elif isinstance(node, int):
            return 'int'
        elif isinstance(node, float):
            return 'float'
        else:
            return 'unknown'

    def evaluate_node(self, node):
        if isinstance(node, NumNode):
            return node.value, None
        
        elif isinstance (node, StringNode):
            return node.value, None
        
        elif isinstance(node, BoolNode):
            return node.value, None
        
        elif isinstance(node, NullNode):
            return 'Null', None
        
        elif isinstance(node, IdNode):
            symbol = self.symbol_table.get(node.name)
            if symbol is None:
                return None, SemanticError(node.pos_start, node.pos_end, f"Variable '{node.name}' is not declared")
            if isinstance(symbol, VarDecNode):
                value, error = self.evaluate_node(symbol.value)
                if error:
                    return None, error
            elif isinstance(symbol, ClanDecNode):
                value = symbol.initial_values
                if isinstance(value, ClanLiteralNode):
                    value = value.values

            return value, None

        elif isinstance(node, (BinOpNode, RelOpNode, LogOpNode, ExponentNode)):
            # Check if this is inside a recursive function call
            inside_recursion = False
            true_parent = node.parent
            while true_parent and hasattr(true_parent, 'parent'):
                if isinstance(true_parent, CurseDecNode) and hasattr(node, 'left') and hasattr(node, 'right'):
                    # Check if either side contains a recursive call to the same function
                    if isinstance(node.left, CurseCallNode) and isinstance(node.right, CurseCallNode):
                        # If both sides call functions, we need isolation
                        inside_recursion = True
                        break
                true_parent = true_parent.parent

            # Only make a copy of scopes if we're in a recursive context
            if inside_recursion:
                original_scopes = copy.deepcopy(self.symbol_table.scopes)
            
            # Evaluate left side
            left_value, error = self.evaluate_node(node.left)
            if error:
                return None, error
            
            # Only restore scopes if needed
            if inside_recursion:
                self.symbol_table.scopes = copy.deepcopy(original_scopes)

            right_value, error = self.evaluate_node(node.right)
            if error:
                return None, error


            if isinstance(left_value, NumNode):
                left_value = left_value.value
            if isinstance(right_value, NumNode):
                right_value = right_value.value

            if left_value == 'Null' or right_value == 'Null':
                error = RTError(node.pos_start, node.pos_end, f"Invalid operation on 'null'")
                return None, error
            
            if not isinstance(node, ExponentNode):
                try:
                    def to_bool(val):
                                if isinstance(val, str):
                                    return True if val != "" else False
                                if isinstance(val, (int, float)):
                                    return val != 0
                                if isinstance(val, bool):
                                    return val
                                return bool(val)
                    
                    if left_value is not None and right_value is not None: 
                        # Convert True/False to 1/0 for arithmetic and comparison
                        if isinstance(left_value, bool):
                            left_value = 1 if left_value else 0
                        if isinstance(right_value, bool):
                            right_value = 1 if right_value else 0

                        if node.op == '+':
                            return left_value + right_value, None
                        elif node.op == '-':
                            result = left_value - right_value
                            print(f"Evaluating subtraction: {left_value} - {right_value} = {result}")
                            return result, None
                        elif node.op == '*':
                            return left_value * right_value, None
                        elif node.op == '/':
                            print(f"\n\n\n\nI REACHED HERE, RIGHT VALUE: {right_value}\n\n\n\n")
                            if right_value == 0 or right_value == 0.0:
                                return None, RTError(node.pos_start, node.pos_end, "Division by zero")
                            result = left_value / right_value
                            if result > 999999999:
                                return None, RTError(node.pos_start, node.pos_end, "Float significant values exceeded limit of 9 digits")
                            if isinstance(result, float):
                                decimal_part = str(result).split('.')[-1]
                                if len(decimal_part) > 7:
                                    result = round(result, 7)
                            return result, None
                        elif node.op == '%':
                            return left_value % right_value, None
                        elif node.op == '==':
                            return left_value == right_value, None
                        elif node.op == '!=':
                            return left_value != right_value, None
                        elif node.op == '<':
                            # Convert string operands to bool (1/0) for comparison
                            if isinstance(left_value, str):
                                left_value = 1 if left_value != "" else 0
                            if isinstance(right_value, str):
                                right_value = 1 if right_value != "" else 0
                            return left_value < right_value, None
                        elif node.op == '>':
                            if isinstance(left_value, str):
                                left_value = 1 if left_value != "" else 0
                            if isinstance(right_value, str):
                                right_value = 1 if right_value != "" else 0
                            return left_value > right_value, None
                        elif node.op == '<=':
                            if isinstance(left_value, str):
                                left_value = 1 if left_value != "" else 0
                            if isinstance(right_value, str):
                                right_value = 1 if right_value != "" else 0
                            return left_value <= right_value, None
                        elif node.op == '>=':
                            if isinstance(left_value, str):
                                left_value = 1 if left_value != "" else 0
                            if isinstance(right_value, str):
                                right_value = 1 if right_value != "" else 0
                            return left_value >= right_value, None
                        elif node.op == '&&':
                            return to_bool(left_value) and to_bool(right_value), None
                        elif node.op == '||':
                            return to_bool(left_value) or to_bool(right_value), None
                        else:
                            return None, RTError(node.pos_start, node.pos_end, f"Unknown operator '{node.op}'")
                    else:
                        return None, RTError(node.pos_start, node.pos_end, "Invalid operation on 'null'")

                except Exception as e:
                    return None, RTError(node.pos_start, node.pos_end, f"Error during operation '{node.op}': {str(e)}")
            else:
                return left_value ** right_value, None
        
        elif isinstance(node, UnaryOpNode):
            if node.op.op == '-' and node.pre is True:
                value, error = self.evaluate_node(node.expr)
                if error:
                    return None, error
                if isinstance(value, NumNode):
                    value = value.value * -1
                elif isinstance(value, (float, int)):
                    value = value * -1
                return value, None
            if node.op.op == '!' and node.pre is True:
                value, error = self.evaluate_node(node.expr)
                if error:
                    return None, error
                if isinstance(value, BoolNode):
                    value = not value.value
                elif isinstance(value, bool):
                    value = not value
                return value, None
            if node.op.op == '++' and node.pre is False:
                value, error = self.evaluate_node(node.expr)
                if error:
                    return None, error
                if isinstance(value, NumNode):
                    value = value.value + 1
                elif isinstance(value, (float, int)):
                    value = value + 1
                return value, None
            if node.op.op == '--' and node.pre is False:
                value, error = self.evaluate_node(node.expr)
                if error:
                    return None, error
                if isinstance(value, NumNode):
                    value = value.value - 1
                elif isinstance(value, (float, int)):
                    value = value - 1
                return value, None
            if node.op.op == '++' and node.pre is True:
                value, error = self.evaluate_node(node.expr)
                if error:
                    return None, error
                if isinstance(value, NumNode):
                    value = value.value + 1
                elif isinstance(value, (float, int)):
                    value = value + 1
                return value, None
            if node.op.op == '--' and node.pre is True:
                value, error = self.evaluate_node(node.expr)
                if error:
                    return None, error
                if isinstance(value, NumNode):
                    value = value.value - 1
                elif isinstance(value, (float, int)):
                    value = value - 1
                return value, None
                
        elif isinstance(node, ClanAccessNode):
            clan = self.symbol_table.get(node.name)
            if clan is None:
                return None, SemanticError(node.pos_start, node.pos_end, f"Clan '{node.name}' is not declared")
            
            if isinstance(clan, ClanDecNode):
                pass
            elif isinstance(clan, VarDecNode):
                index1, error = self.evaluate_node(node.index1)
                if error:
                    return None, error
                try: 
                    return clan.value.value[index1], None
                except IndexError:
                    return None, SemanticError(node.pos_start, node.pos_end, f"Index out of bounds for '{node.name}'")
            elif isinstance(clan, str):
                index1, error = self.evaluate_node(node.index1)
                if error:
                    return None, error
                return clan[index1], None
            else:
                self.error = (SemanticError(node.pos_start, node.pos_end, f"'{node.name}' is not a clan"))
            
            index1, error = self.evaluate_node(node.index1)
            if error:
                return None, error
            size1, error = self.evaluate_node(clan.size1)
            if error:
                return None, error
            
            if not isinstance(index1, int) or index1 < 0 or (clan.size1 and index1 >= size1):
                return None, SemanticError(node.pos_start, node.pos_end, f"Index 1 out of bounds for clan '{node.name}'")
            
            if node.index2:
                index2, error = self.evaluate_node(node.index2)
                if error:
                    return None, error
                size2, error = self.evaluate_node(clan.size2)
                if error:
                    return None, error
                
                if not isinstance(index2, int) or index2 < 0 or (clan.size2 and index2 >= size2):
                    return None, SemanticError(node.pos_start, node.pos_end, f"Index 2 out of bounds for clan '{node.name}'")
                
                try:
                    value  = clan.initial_values[index1].values[index2]
                    if isinstance(value, StringNode):
                        value = value.value
                    elif isinstance(value, NumNode):
                        value = value.value
                    elif isinstance(value, BoolNode):
                        value = value.value
                    else: 
                        value = value
                    return value, None
                except IndexError:
                    print(f"VALUES: {clan.initial_values}")
                    return None, SemanticError(node.pos_start, node.pos_end, f"Invalid access at [{index1}][{index2}] for clan '{node.name}'")
            else:
                try:
                    value = clan.initial_values.values[index1]
                    if isinstance(value, StringNode):
                        value = value.value
                    elif isinstance(value, NumNode):
                        value = value.value
                    elif isinstance(value, BoolNode):
                        value = value.value
                    else: 
                        value = value
                    return value, None
                except IndexError:
                    return None, SemanticError(node.pos_start, node.pos_end, f"Invalid access at [{index1}] for clan '{node.name}'")

        elif isinstance(node, CurseCallNode):
            # Retrieve the curse declaration from the symbol table
            curse_dec_node = self.symbol_table.get(node.name)
            if curse_dec_node is None:
                error = SemanticError(node.pos_start, node.pos_end, f"Curse '{node.name}' is not declared")
                return None, error

            if not isinstance(curse_dec_node, CurseDecNode):
                error = SemanticError(node.pos_start, node.pos_end, f"'{node.name}' is not a curse")
                return None, error

            # Check if the number of arguments matches the number of parameters
            if len(node.arguments) != len(curse_dec_node.parameters):
                error = SemanticError(
                    node.pos_start,
                    node.pos_end,
                    f"Argument count mismatch for curse '{node.name}': expected {len(curse_dec_node.parameters)}, got {len(node.arguments)}"
                )
                return None, error

            # Evaluate arguments and map them to parameters
            self.symbol_table.push() # Enter new scope for curse call
            for param, arg in zip(curse_dec_node.parameters, node.arguments):
                arg_value, error = self.evaluate_node(arg)
                if error:
                    error = error
                    return None, error

                # Type checking
                if param.datatype == 'int' and isinstance(arg_value, float):
                    arg_value = int(arg_value) # Convert float to integer
                elif param.datatype == 'float' and isinstance(arg_value, int):
                    arg_value = float(arg_value) # Convert integer to float
                elif param.datatype != self.infer_type(arg_value):
                    self.error = SemanticError(
                        node.pos_start,
                        node.pos_end,
                        f"Type mismatch for parameter '{param.name}': expected {param.datatype}, got {self.infer_type(arg_value)}"
                    )
                    return None, None

                # Add parameter to the local symbol table
                self.symbol_table.set_local(param.name, VarDecNode(False, param.datatype, param.name, NumNode(arg_value, None, None), param.pos_start, param.pos_end))

            # Execute the body of the curse
            if curse_dec_node.datatype is None:
                try:
                    self.visit(curse_dec_node.body, curse_dec_node)
                    self.symbol_table.pop()
                    return None, None
                except ReturnException:
                    # If a return statement is encountered, exit the curse call
                    self.symbol_table.pop()
                    return None, None
                
            else:
                recall_val = None
                try: 
                    self.visit(curse_dec_node.body, curse_dec_node)
                except ReturnException as e:
                    recall_val = e.value
                self.symbol_table.pop()
                print(f'\n\n\nEVALUATE CURSECALL RECALL VALUE: {recall_val}\n\n\n')
                if recall_val is not None:
                    if isinstance(recall_val, NumNode):
                        value = recall_val.value
                    elif isinstance(recall_val, StringNode):
                        value = recall_val.value
                    elif isinstance(recall_val, BoolNode):
                        value = recall_val.value
                    else:
                        value = recall_val
                    return value, None
                else:
                    if self.error:
                        return None, None
                    else: return None, RTError(node.pos_start, node.pos_end, f"Curse '{node.name}' did not return a value")
        
        elif isinstance(node, LenNode):
            print(f"Visiting LenNode with name: {node.name}")

            # Retrieve the clan from the symbol table
            if isinstance(node.name, IdNode):
                symbol = self.symbol_table.get(node.name.name)
                if symbol is None:
                    return None, SemanticError(node.pos_start, node.pos_end, f"'{node.name.name}' is not declared")
            elif isinstance(node.name, CleaveNode):
                symbol = node.name.arg1
            elif isinstance(node.name, ClanAccessNode):
                symbol = self.symbol_table.get(node.name.name)
                if symbol is None:
                    return None, SemanticError(node.pos_start, node.pos_end, f"'{node.name.name}' is not declared")
            elif isinstance(node.name, ClanDecNode):
                symbol = node.name
            elif isinstance(node.name, StringNode):
                symbol = node.name.value
            elif isinstance(node.name, str):
                symbol = node.name
            else: 
                symbol = node.name.value

            if not isinstance(symbol, (ClanDecNode, StringNode, VarDecNode, str)):
                if isinstance(symbol, VarDecNode):
                    if symbol.datatype != 'string':
                        self.error = SemanticError(node.pos_start, node.pos_end, f"'{node.name}' is not a clan or string")
                    else: pass
                else: 
                    self.error = SemanticError(node.pos_start, node.pos_end, f"Expected clan or string, got {type(symbol)}")
                    return None, SemanticError(node.pos_start, node.pos_end, f"Expected clan or string")

            # Determine the length based on the dimensions
            if isinstance(symbol, ClanDecNode):
                if symbol.size1:
                    size1, error = self.evaluate_node(symbol.size1)
                    if error:
                        return None, error
                    return size1, None
                else:
                    clan_lit = symbol.initial_values
                    if not isinstance(clan_lit, ClanLiteralNode):
                        return None, SemanticError(node.pos_start, node.pos_end, f"Expected ClanLiteralNode for clan '{node.name}'")
                    if isinstance(clan_lit.values, list):
                        return len(clan_lit.values), None
                    else:
                        return sum(1 for clan in clan_lit.values if isinstance(clan, ClanLiteralNode)), None
                
            elif isinstance(symbol, StringNode):
                return len(StringNode.value), None
            
            elif isinstance(symbol, str):
                return len(symbol), None
            
            elif isinstance(symbol, VarDecNode):
                if symbol.datatype == 'string':
                    return len(symbol.value.value), None
                else:
                    if isinstance(symbol, str):
                        start, error = self.evaluate_node(node.index1)
                        if error:
                            return None, error
                        end, error = self.evaluate_node(node.index2)
                        if error:
                            return None, error
                        return symbol[start:start + end], None

                    elif isinstance(symbol, ClanDecNode):
                        start, error = self.evaluate_node(node.index1)
                        if error:
                            return None, error
                        end, error = self.evaluate_node(node.index2)
                        if error:
                            return None, error

                        if not isinstance(start, int) or not isinstance(end, int):
                            return None, SemanticError(node.pos_start, node.pos_end, f"Indexes must be integers")

                        if start < 0 or end < 0:
                            return None, SemanticError(node.pos_start, node.pos_end, f"Indexes must be non-negative")

                        result = []
                        for i in range(start, start + end):
                            if i >= len(symbol.initial_values.values):
                                break
                            result.append(symbol.initial_values.values[i])

                        return result, None

                    return None, SemanticError(node.pos_start, node.pos_end, f"'{node.name.name}' is not a clan or string")

        elif isinstance(node, CleaveNode):
            if isinstance(node.arg1, StringNode):
                symbol = node.arg1
            else:
                symbol = self.symbol_table.get(node.arg1.name)
            if symbol is None:
                return None, SemanticError(node.pos_start, node.pos_end, f"'{node.arg1.name}' is not declared")

            if isinstance(symbol, VarDecNode) and symbol.datatype == 'string':
                string_value = symbol.value.value
                start, error = self.evaluate_node(node.index1)
                if error:
                    return None, error
                length, error = self.evaluate_node(node.index2)
                if error:
                    return None, error

                if not isinstance(start, int) or not isinstance(length, int):
                    return None, SemanticError(node.pos_start, node.pos_end, f"Indexes must be integers")

                if start < 0:
                    start = max(len(string_value) + start, 0)

                result = string_value[start:start + length]
                
                return result, None

            elif isinstance(symbol, StringNode):
                string_value = symbol.value
                start, error = self.evaluate_node(node.index1)
                if error:
                    return None, error
                length, error = self.evaluate_node(node.index2)
                if error:
                    return None, error

                if not isinstance(start, int) or not isinstance(length, int):
                    return None, SemanticError(node.pos_start, node.pos_end, f"Indexes must be integers")

                if start < 0:
                    start = max(len(string_value) + start, 0)

                result = string_value[start:start + length]
                
                return result, None

            elif isinstance(symbol, ClanDecNode):
                start, error = self.evaluate_node(node.index1)
                if error:
                    return None, error
                length, error = self.evaluate_node(node.index2)
                if error:
                    return None, error

                if not isinstance(start, int) or not isinstance(length, int):
                    return None, SemanticError(node.pos_start, node.pos_end, f"Indexes must be integers")

                if start < 0:
                    start = max(len(symbol.initial_values.values) + start, 0)

                result = []
                for i in range(start, start + length):
                    if i >= len(symbol.initial_values.values):
                        break
                    result.append(symbol.initial_values.values[i])
                print(f'Interpreter CleaveNode result: {result}')
                return ClanLiteralNode(result), None

            else:
                return None, SemanticError(node.pos_start, node.pos_end, f"'{node.arg1.name}' is not a string or clan")

        elif isinstance(node, DismantleNode):
            string_value, error = self.evaluate_node(node.value)
            if error:
                return None, error

            delimiter_value, error = self.evaluate_node(node.delimiter)
            if error:
                return None, error

            if not isinstance(string_value, str):
                return None, SemanticError(node.pos_start, node.pos_end, f"Expected a string for dismantle, got {type(string_value).__name__}")

            if not isinstance(delimiter_value, str):
                return None, SemanticError(node.pos_start, node.pos_end, f"Expected a string as delimiter, got {type(delimiter_value).__name__}")

            if not delimiter_value:
                return None, SemanticError(node.pos_start, node.pos_end, "Delimiter cannot be an empty string")
            # Split the string using the delimiter
            split_values = string_value.split(delimiter_value)
            result = [StringNode(value, None, None) for value in split_values]
            return ClanLiteralNode(result), None

        elif isinstance(node, (str, int, float)):
            return node, None
        
        else:
            return None, None
